---
name: 'Get & Cache dependencies for Node.js'
description: 'Checkout code, get & cache dependencies for Node.js projects'
runs:
  using: 'composite'
  steps:
  - name: Cache dependencies
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true'
    run: npm ci
    shell: bash
